### ISSUE TITLE
NBGWAS Website updates

### ISSUE THREAD

**Issue by shfong** [idekerlab/nbgwas_rest#14]
Great work with the APIs and website! I just have some minor tweaks below, separated by priority.  

### High priority (before we submit) 
- Please add a "Run Schizophrenia Example" button at the top. This button should load the SNP file located in http://nbgwas.ucsd.edu/nagadata/schizophrenia.txt [http://nbgwas.ucsd.edu/nagadata/schizophrenia.txt]. Run this with "hg18". 

- Add a blurb under "Upload SNP Level Summary" that describes what should the file look like. 

- Change "Window" to "Window Size"
- Change "Alpha" to "Restart Probability" 
- Change part of the text under "Alpha" to "...representing the restart probability.... Larger values increases the likelihood of starting with the original distribution again" 
- Capitalize Huang, Cell Systems 2018 (Add link) 

- Add a Data tab linking to http://nbgwas.ucsd.edu/nagadata

- Make the "build" website the landing page
- Change button to "Upload SNP Level Summary" with title "GWAS Summary Statistics" 
- Move this button above the network UUID

### Low Priority (after we submit/long term) 
- Add a link to the paper (after it's published) 

In the results page:
- Add a network view
- Add download network option

**Comment by coleslaw481** [comment]
All high priority tasks have been completed. Two tickets have been created for the low priority tasks and can be found here:

https://github.com/BrettJSettle/NBGWAS-Frontend/issues/1
https://github.com/BrettJSettle/NBGWAS-Frontend/issues/2

Closing ticket, please re-open or make a new ticket if anything else is needed.
